config/routes.rb
Marketplace::Application.routes.draw do
  root :to => 'welcome#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'signup', to: 'trainer#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :trainers
  resources :sessions
  resources :ratings
  resources :trainercertifications
  

  get 'certifications/:id', to: 'certifications#show', as: 'certifications'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  attr_accessible :abbreviation, :description, :name

  validates :name, :abbreviation, :uniqueness => true

  has_many :trainer_certifications
  has_many :trainers, through: :trainer_certifications
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :rating, :trainer_id

  validates :trainer_id, :rating, :presence => true
  validates :rating, :inclusion => 1..10

  belongs_to :trainer

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :email, :password, :password_confirmation

  validates :name, :email, :presence => true
  validates :email, :uniqueness => { :case_sensitive => false }
  validates :email, :format => { :with => /@/, :message => " is invalid" }

  has_many :trainer_certifications, dependent: :destroy
  has_many :certifications, through: :trainer_certifications
  has_many :ratings

  def average_rating
    counter = 0
    a = self.ratings.size.to_f
    self.ratings.each do |rating|
      size = rating.rating
      counter += size
    end
    counter/a
  end
end

app/models/trainer_certification.rb
class TrainerCertification < ActiveRecord::Base
  attr_accessible :certification_id, :trainer_id

  belongs_to :trainer
  belongs_to :certification

  validates_uniqueness_of :certification_id, :scope => :trainer_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= Trainer.find(session[:trainer_id]) if session[:trainer_id]
  end
  
  helper_method :current_user

end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController

  def show
    @certification = Certification.find(params[:id])
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @rating = Rating.new
  end

  def create
    @rating = Rating.new(params[:rating])
    if @rating.save
      redirect_to request.referer, notice: "Thanks for the rating!"
    else
      redirect_to request.referer, alert: "The rating didn't work"
    end
  end

  def index
    @ratings = Rating.all
  end

  def show
    @rating = Rating.find(params[:id])
  end

  def edit
    @rating = Rating.find(params[:id])
  end

  def update
    rRating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    trainer = Trainer.find_by_email(params[:email])
    if trainer && trainer.authenticate(params[:password])
      session[:trainer_id] = trainer.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render "new"
    end
  end

  def destroy
    session[:trainer_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/trainercertifications_controller.rb
class TrainerCertificationsController < ApplicationController

  def new
    @trainercertification = Trainercertification.new
  end

  def create
    @trainercertification = Trainercertification.new(params[:trainercertification])
    if @trainercertification.save
      redirect_to request.referer, notice: "Thanks for the trainercertification!"
    else
      redirect_to request.referer, alert: "The trainercertification didn't work"
    end
  end

  def index
    @trainercertifications = Trainercertification.all
  end

  def show
    @trainercertification = Trainercertification.find(params[:id])
  end

  def edit
    @trainercertification = Trainercertification.find(params[:id])
  end

  def update
    rtrainercertification = Trainercertification.find(params[:id])

    respond_to do |format|
      if @trainercertification.update_attributes(params[:trainercertification])
        format.html { redirect_to @trainercertification, notice: 'trainercertification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trainercertification.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trainercertification = Trainercertification.find(params[:id])
    @trainercertification.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  def new
    @trainer = Trainer.new
  end

  def create
    @trainer = Trainer.new(params[:trainer])
    if @trainer.save
      session[:trainer_id] = @trainer.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end

  def edit
    @trainer = Trainer.find(params[:id])
  end

  def update
    @trainer = Trainer.find(params[:id])

    respond_to do |format|
      if @trainer.update_attributes(params[:trainer])
        format.html { redirect_to @trainer, notice: 'trainer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trainer = Trainer.find(params[:id])
    @trainer.destroy

    respond_to do |format|
      format.html { redirect_to exercises_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/certifications/show.html.erb
<p>
  <b>Name:</b>
  <%= @certification.name %>
</p>

<p>
  <b>Abbreviation:</b>
  <%= @certification.abbreviation %>
</p>

<p>
  <b>Description:</b>
  <%= @certification.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Marketplace</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Marketplace", root_path, :class => "navbar-brand" %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li>
          <a href="../getting-started">Getting started</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless current_user %>
          <li>
            <%= link_to "Register", new_trainer_path %>
          </li>
          <li>
            <%= link_to "Log In", new_session_path %>
          </li>
        <% else %>
          <li>
            <%= link_to current_user.email, trainer_path(current_user.id) %>
          </li>
          <li>
            <%= link_to "Log Out", session_path("current"), method: "delete" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<div class="container">

<div class="row-fluid">
<div class="span8">
<% if flash.notice %>
  <div class="alert alert-info">
    <%= flash.notice %>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-error">
    <%= flash.alert %>
  </div>
<% end %>       
</div>
</div>

<%= yield %>

</div>

</body>
</html>

app/views/trainers/_form.html.erb
<%= form_for @trainer do |f| %>
  <% if @trainer.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @trainer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <%= f.submit(:class => "btn btn-primary") %>
  </div>
<% end %>

app/views/trainers/edit.html.erb
<h1>Edit Trainer</h1>

<%= render 'form' %>

<%= link_to "Show", @trainer %>
<%= link_to "Back", trainers_path %>

app/views/trainers/index.html.erb
<h1>Listing Trainers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trainers.each do |trainer| %>
  <tr>
    <td><%= trainer.name %></td>
    <td><%= trainer.email %></td>
    <td><%= link_to 'Show', trainer %></td>
    <td><%= link_to 'Edit', edit_trainer_path(trainer) %></td>
    <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/trainers/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/trainers/show.html.erb
<p>
  <b>Name:</b>
  <%= @trainer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @trainer.email %>
</p>

<% if @trainer.ratings.size > 1 %>
  <p>
    <b>Rating (out of 10):</b>
    <%= @trainer.average_rating %>
  </p>
<% end %>

<%= form_for (Rating.new) do |f| %>

  <div class="form-group">
    <%= f.hidden_field :trainer_id, :value => @trainer.id %>
  </div>
  <div class="form-group">
    <%= f.label :rating, "Rating between 1 and 10" %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="form-group">
    <%= f.submit(:class => "btn btn-primary") %>
  </div>
<% end %>


<%= link_to 'Edit', edit_trainer_path(@trainer) %> |
<%= link_to 'Back', trainers_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>